# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: A
  jobs:
    - job: A
      displayName: JobA
      steps:
        - script: echo Job A
 
- stage: B
  jobs:
    - job: B
      displayName: JobB
      steps:
        - script: echo Job B
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
